### PR TITLE
Add alt text for banner buttons

### PR DESCRIPTION
**Pull request by denar90**
It fixes Lighthouse warning that buttons don't have alt text in banner, It affects accessibility score across all demos.
I understand that it's compiled OSS version but good to have to not forget about fix :)

### CODE REVIEW

**Comment by smnh** [comment]
@denar90 Also, I didn't notice it in your previous PR, but there too, the changes were done only in dist folder. Meaning, next time we make a commit, your changes will be lost.

**Comment by denar90** [comment]
Yup, looks like only dist folder is open-sourced, can you share link to src folder? I'll be happy to add updates there)

**Comment by smnh** [comment]
invited you to our org

you will want to change files in
https://github.com/stackbithq/stackbit-factory src/unibit

Simon Hanukaev
CTO, [image: Stackbit Logo] Stackbit <https://www.stackbit.com>

**Comment by denar90** [comment]
Changes were moved to stackbit-factory.

**Pull request closed without merging**
